//! Command-line surface for `classos-session` (spec §39, §126). Kept
//! host-portable so argument parsing is unit-testable on any host.

use clap::Parser;

#[derive(Parser, Debug, Clone, PartialEq, Eq)]
#[command(name = "classos-session", about = "ClassOS Session Host")]
pub struct Cli {
    /// The Windows session id this Session Host was launched for. Purely
    /// informational on this side — the Service independently re-derives
    /// it via `ProcessIdToSessionId`/`GetNamedPipeClientProcessId` and
    /// never trusts this value (spec §59-60, §132).
    #[arg(long = "session-id")]
    pub session_id: u32,

    /// The Named Pipe name to connect to, generated by the Service for
    /// this specific launch (spec §41-42).
    #[arg(long = "pipe")]
    pub pipe: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_session_id_and_pipe() {
        let cli = Cli::parse_from([
            "classos-session",
            "--session-id",
            "1",
            "--pipe",
            r"\\.\pipe\classos\session-1-abc",
        ]);
        assert_eq!(cli.session_id, 1);
        assert_eq!(cli.pipe, r"\\.\pipe\classos\session-1-abc");
    }
}
